import { Metadata } from "next";
import { Cedarville_Cursive, Josefin_Sans, Poppins } from "next/font/google";
import "./globals.css";
import { AppProviders } from "./components/AppProviders";
import Custom from "./components/Custom";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-Poppins",
});

const josefin = Josefin_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-Josefin",
});

const cursive = Cedarville_Cursive({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-Cursive",
});

export const metadata: Metadata = {
  title: "E-Learning",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${josefin.variable} ${cursive.variable} !bg-white bg-no-repeat dark:bg-gradient-to-b dark:from-gray-900 dark:to-black duration-300`}
      >
        <AppProviders>
          <Custom>{children}</Custom>
        </AppProviders>
      </body>
    </html>
  );
}